---
name: 'OPI Network API CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'common/v1/**'
      - 'common/Makefile'
      - 'network/v1/**'
      - 'network/Makefile'
      - '.github/workflows/network.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'common/v1/**'
      - 'common/Makefile'
      - 'network/v1/**'
      - 'network/Makefile'
      - '.github/workflows/network.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: network-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-network-protobuf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@0648fd6fd6801dcae14b6299cc1b23187d3cb797

    - name: Build protobufs
      run: make
      working-directory: network

    - name: Check uncomitted auto generated protobufs
      run: git diff --exit-code
      working-directory: network

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        path: network/v1/gen/go/*.pb.go
        retention-days: 1
