---
name: 'OPI Storage API CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'common/v1/**'
      - 'common/Makefile'
      - 'storage/v1/**'
      - 'storage/Makefile'
      - '.github/workflows/storage.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'common/v1/**'
      - 'common/Makefile'
      - 'storage/v1/**'
      - 'storage/Makefile'
      - '.github/workflows/storage.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: storage-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-storage-protobuf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325

    - name: Build protobufs
      run: make
      working-directory: storage

    - name: Check uncomitted auto generated protobufs
      run: git diff --exit-code
      working-directory: storage

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        path: storage/v1/gen/go/*.pb.go
        retention-days: 1
